/* ── minimal-pair contrast drills ──
   The distinctions that actually cost a beginner marks in Japanese are not vocabulary, they
   are orthographic: the small っ in 学校 (がっこう, not がこう), the small ゃ in 感謝
   (かんしゃ, not かんしや), the long vowel in 高校 (こうこう, not ここう). A learner can know
   a word perfectly well as meaning-plus-sound and still spell it wrong every time, and a
   recognition-based system will never notice — the card keeps coming back "correct".

   So the drill shows the word and asks which SPELLING is right, against distractors that
   differ by exactly one of these features. Wrong options are generated by degrading the
   real reading rather than by pulling other words, which is what makes them minimal pairs:
   the only thing under test is the feature itself.

   Everything here is derived from the reading the card already carries. No new data. */

export const FEATURE = { SOKUON: "sokuon", YOON: "yoon", LONG: "long" };
export const FEATURE_LABEL = {
  sokuon: "small っ",
  yoon:   "small ゃゅょ",
  long:   "long vowel",
};
/* What the learner should take away when they get it wrong. Phrased as the rule, not as
   "incorrect" — the point of a minimal pair is that the contrast itself is the lesson. */
export const FEATURE_NOTE = {
  sokuon: "The small っ doubles the next consonant — it is a beat of silence, not a と.",
  yoon:   "Small ゃゅょ fuse with the kana before them into one beat; the full-size ones are their own beat.",
  long:   "A long vowel is two beats. Dropping it makes a different word.",
};

const SMALL_YOON = { "ゃ": "や", "ゅ": "ゆ", "ょ": "よ" };
/* A long vowel in kana is written as the vowel kana FOLLOWING a mora of the same vowel
   row — こう is a long o exactly as おう is, けい is a long e, くう a long u. Matching only
   the literal pairs おう/うう/えい misses almost every real case: 学校 がっこう and 高校
   こうこう both lengthen after a k-row mora, not after お. So the rule is by row. */
const ROW = {
  "あ": "あかさたなはまやらわがざだばぱ",
  "い": "いきしちにひみりぎじぢびぴ",
  "う": "うくすつぬふむゆるぐずづぶぷゅ",
  "え": "えけせてねへめれげぜでべぺ",
  "お": "おこそとのほもよろごぞどぼぽょ",
};
/* Which vowel kana lengthens which row. お is lengthened by う (not お) in the overwhelming
   majority of words — おお exists (大きい) but is the exception, and both are handled. */
const LENGTHENER = { "あ": ["あ"], "い": ["い"], "う": ["う"], "え": ["い", "え"], "お": ["う", "お"] };
/* Only used when INSERTING a wrong lengthener; deletion still recognises every real form. */
const INSERT_LENGTHENER = { "お": "う", "う": "う", "え": "い" };

/** Every single-feature degradation of a reading, each tagged with the feature it tests.
 *  Deliberately one change per variant: two changes stop being a minimal pair. */
export function variantsFor(reading) {
  const out = [];
  const seen = new Set([reading]);
  const push = (v, feature) => {
    if (!v || v === reading || seen.has(v)) return;
    seen.add(v);
    out.push({ reading: v, feature });
  };
  if (!reading) return out;

  // small っ: drop it (a real, extremely common beginner error)
  for (let i = 0; i < reading.length; i++) {
    if (reading[i] === "っ") push(reading.slice(0, i) + reading.slice(i + 1), FEATURE.SOKUON);
  }
  // small ゃゅょ: write them full-size
  for (let i = 0; i < reading.length; i++) {
    const big = SMALL_YOON[reading[i]];
    if (big) push(reading.slice(0, i) + big + reading.slice(i + 1), FEATURE.YOON);
  }
  // long vowels: drop the lengthening kana, collapsing two beats into one
  for (let i = 1; i < reading.length; i++) {
    const prev = reading[i - 1], here = reading[i];
    for (const vowel of Object.keys(ROW)) {
      if (!ROW[vowel].includes(prev)) continue;
      if (!LENGTHENER[vowel].includes(here)) continue;
      push(reading.slice(0, i) + reading.slice(i + 1), FEATURE.LONG);
      break;
    }
  }
  /* The inverse errors. Learners do not only DROP these features, they insert them where
     they do not belong — がこう for 学校 and ねこう for 猫 are both things people write. A
     drill built only from deletions teaches "pick the longer one", which is a shape rule,
     not a Japanese one. */
  // spurious っ before a mora that could legally follow one
  const SOKUON_BEFORE = "かきくけこさしすせそたちつてとぱぴぷぺぽ";
  for (let i = 1; i < reading.length; i++) {
    if (reading[i - 1] === "っ") continue;
    if (SOKUON_BEFORE.includes(reading[i])) {
      push(reading.slice(0, i) + "っ" + reading.slice(i), FEATURE.SOKUON);
    }
  }
  /* Spurious lengthener — but only the three that occur in real Japanese words, and so are
     the three learners actually over-apply: o-row + う, u-row + う, e-row + い. Generating
     ああ and いい insertions as well pushed coverage higher but filled the options with
     strings nobody would ever write (があっこう, かあんしゃ), and an implausible distractor
     is worse than no distractor: it can be eliminated on sight, which turns a discrimination
     test into a spot-the-weird-one test. */
  for (let i = 0; i < reading.length; i++) {
    const here = reading[i], next = reading[i + 1];
    for (const vowel of ["お", "う", "え"]) {
      if (!ROW[vowel].includes(here)) continue;
      const lengthener = INSERT_LENGTHENER[vowel];
      if (next === lengthener) break;                 // already long: leave it alone
      /* ...and do not lengthen a lengthener. At the う of がっこう this would otherwise
         produce がっこうう, which is not an error anyone makes. */
      const prev = reading[i - 1];
      if (prev && (here === "う" || here === "い")) {
        const lengthensPrev = ["お", "う", "え"].some((v) => ROW[v].includes(prev) && INSERT_LENGTHENER[v] === here);
        if (lengthensPrev) break;
      }
      push(reading.slice(0, i + 1) + lengthener + reading.slice(i + 1), FEATURE.LONG);
      break;
    }
  }
  return out;
}

/** Does this card have anything worth contrasting? Cheap enough to filter a whole deck. */
export function hasContrast(card) {
  return !!(card && card.reading && variantsFor(card.reading).length > 0);
}

/* Deterministic shuffle so the same card does not reshuffle its options on every render —
   an option that moves under the cursor is its own small usability bug. */
function shuffle(list, seed) {
  const a = list.slice();
  let s = (seed >>> 0) || 1;
  for (let i = a.length - 1; i > 0; i--) {
    s = (s * 1664525 + 1013904223) >>> 0;
    const j = s % (i + 1);
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

/** One drill, or null when the card has no contrastable feature.
 *  The feature reported is the one the DISTRACTORS test, which is what the learner is
 *  actually being asked to discriminate. */
export function contrastDrill(card, opts = {}) {
  const n = Math.max(2, Math.min(4, opts.options || 4));
  const seed = opts.seed || 0;
  if (!card || !card.reading) return null;
  const variants = variantsFor(card.reading);
  if (!variants.length) return null;

  /* Prefer distractors that all probe the SAME feature: mixing a sokuon error with a long
     vowel error lets the learner rule options out by shape instead of by hearing the word. */
  const byFeature = new Map();
  for (const v of variants) {
    if (!byFeature.has(v.feature)) byFeature.set(v.feature, []);
    byFeature.get(v.feature).push(v);
  }
  const features = [...byFeature.keys()];
  const feature = features[seed % features.length];
  let pool = byFeature.get(feature);
  if (pool.length < n - 1) {                       // top up from the others rather than shrink the drill
    const rest = variants.filter((v) => v.feature !== feature);
    pool = pool.concat(rest);
  }
  const wrong = pool.slice(0, n - 1).map((v) => v.reading);
  if (!wrong.length) return null;

  return {
    id: card.id,
    term: card.term,
    meaning: card.meaning || "",
    emoji: card.emoji || "",
    answer: card.reading,
    feature,
    label: FEATURE_LABEL[feature],
    note: FEATURE_NOTE[feature],
    options: shuffle([card.reading, ...wrong], seed + card.term.length),
  };
}

/** A set of drills over a deck, weakest-first-ish via the caller's ordering, deduped by id. */
export function contrastSet(cards = [], n = 8, opts = {}) {
  const seed = opts.seed || 0;
  const out = [];
  const used = new Set();
  for (const c of cards) {
    if (out.length >= n) break;
    if (!c || used.has(c.id)) continue;
    const d = contrastDrill(c, { seed: seed + out.length, options: opts.options });
    if (d) { out.push(d); used.add(c.id); }
  }
  return out;
}
